// GENERATED by scripts/luna_audio.py — do not edit by hand.
export const LUNA_AUDIO: Record<string, (number | undefined)[]> = {
  'book-1-big-feelings': [
    require('@/assets/luna/audio/book-1-big-feelings/p0.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p1.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p2.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p3.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p4.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p5.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p6.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p7.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p8.mp3'),
    require('@/assets/luna/audio/book-1-big-feelings/p9.mp3'),
  ],
  'book-2-lost-star': [
    require('@/assets/luna/audio/book-2-lost-star/p0.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p1.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p2.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p3.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p4.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p5.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p6.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p7.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p8.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p9.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p10.mp3'),
    require('@/assets/luna/audio/book-2-lost-star/p11.mp3'),
  ],
};
