// Narration for Luna books: book id → one mp3 per page (index = page number).
// GENERATED by scripts/luna_audio.py — run it once on a computer with internet:
//   pip install edge-tts
//   python scripts/luna_audio.py
// Until it has run, this map is empty and the reader simply hides the «Listen» button.
export const LUNA_AUDIO: Record<string, (number | undefined)[]> = {};
