"""Luna kitoblari uchun ovozli o'qish (mp3) yaratadi — o'zbekcha neyron ovoz (Microsoft Edge TTS).

Ishlatish (internet kerak, loyiha papkasida):
    pip install edge-tts
    python scripts/luna_audio.py            # standart ayol ovozi: Madina
    python scripts/luna_audio.py --voice uz-UZ-SardorNeural

Natija:
    assets/luna/audio/<kitob-id>/p<N>.mp3  — har sahifaga bitta fayl
    constants/lunaAudio.ts                 — ilova shu fayldan o'qiydi (avtomatik yoziladi)
Keyin Expo serverni qayta ishga tushiring — o'quvchida «Tinglash» tugmasi paydo bo'ladi.
"""
import argparse
import asyncio
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOOKS_TS = os.path.join(ROOT, "constants", "lunaBooks.ts")
OUT_DIR = os.path.join(ROOT, "assets", "luna", "audio")
MAP_TS = os.path.join(ROOT, "constants", "lunaAudio.ts")


def read_books():
    """lunaBooks.ts → [(book_id, [page_text, ...])] in page order."""
    src = open(BOOKS_TS, encoding="utf-8").read()
    starts = [(m.start(), m.group(1)) for m in re.finditer(r'\bid:\s*"(book-[^"]+)"', src)]
    books = []
    for i, (pos, book_id) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(src)
        texts = [json.loads('"' + t + '"') for t in re.findall(r'textUz:\s*"((?:[^"\\]|\\.)*)"', src[pos:end])]
        books.append((book_id, texts))
    return books


def speakable(text):
    """Bolaga o'qish uchun: «XURSAND» kabi katta harfli so'zlarni oddiy yozuvga, qatorlarni pauzaga."""
    text = re.sub(r"\b([A-ZʻʼO'G'ŞÇ]{3,})\b", lambda m: m.group(1).capitalize(), text)
    return text.replace("\n", " ... ")


async def build(voice, rate):
    import edge_tts

    lines = [
        "// GENERATED by scripts/luna_audio.py — do not edit by hand.",
        "export const LUNA_AUDIO: Record<string, (number | undefined)[]> = {",
    ]
    for book_id, pages in read_books():
        folder = os.path.join(OUT_DIR, book_id)
        os.makedirs(folder, exist_ok=True)
        requires = []
        for n, text in enumerate(pages):
            path = os.path.join(folder, f"p{n}.mp3")
            await edge_tts.Communicate(speakable(text), voice, rate=rate).save(path)
            print(f"  {book_id} p{n}: {os.path.getsize(path) // 1024} KB")
            requires.append(f"require('@/assets/luna/audio/{book_id}/p{n}.mp3')")
        lines.append(f"  '{book_id}': [\n    " + ",\n    ".join(requires) + ",\n  ],")
    lines.append("};")
    open(MAP_TS, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("OK →", MAP_TS)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--voice", default="uz-UZ-MadinaNeural")
    ap.add_argument("--rate", default="-12%", help="sekinroq o'qish uchun manfiy foiz")
    a = ap.parse_args()
    asyncio.run(build(a.voice, a.rate))
